# Generated by Django 5.0.6 on 2024-07-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatepreviousschool',
            name='date_history',
            field=models.CharField(blank=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='candidatepreviousschool',
            name='date_qualification',
            field=models.CharField(blank=True, verbose_name='Date'),
        ),
    ]
