# Generated by Django 5.0.6 on 2024-07-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.IntegerField(choices=[(1, 'about us summary'), (2, 'mission'), (3, 'vision'), (4, 'event'), (5, 'about us full'), (6, 'offer'), (7, 'creed'), (8, 'core values'), (9, 'school anthem'), (10, 'school responsibilty pledge'), (11, 'creche subjects'), (12, 'nursery subjects'), (13, 'primary subjects'), (14, 'junior secondary subjects'), (15, 'senior secondary subjects')], default=4, verbose_name='Post category'),
        ),
    ]
