# Generated by Django 5.0.6 on 2024-07-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateimage',
            name='img_use',
            field=models.CharField(choices=[('events', 'events'), ('homepage', 'homepage'), ('others', 'others'), ('labs', 'labs'), ('reception', 'reception'), ('workshops', 'workshops'), ('school_building', 'school_buiding'), ('sports', 'sports')], default='others', verbose_name='Page image assignment'),
        ),
    ]
