# Generated by Django 4.2.6 on 2023-12-28 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Home",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=3000, unique=True)),
                ("welcome", models.TextField(verbose_name="Homepage welcome address")),
            ],
        ),
        migrations.CreateModel(
            name="SchoolVision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motto", models.CharField(max_length=50)),
                ("vision", models.TextField(verbose_name="School vision")),
                ("mission", models.TextField(verbose_name="School mission")),
                ("creed", models.TextField(verbose_name="School creed")),
                ("core_values", models.TextField(verbose_name="Core values")),
            ],
        ),
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_history", models.TextField(verbose_name="School History")),
                (
                    "school_owner_welcome_address",
                    models.TextField(verbose_name="School Owner Welcome Address"),
                ),
                ("student_leadership", models.TextField()),
                ("staff_report", models.TextField(verbose_name="Our Staff")),
                (
                    "result_report",
                    models.TextField(verbose_name="Result and Honours Roll"),
                ),
                (
                    "school_vision_and_mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.schoolvision",
                    ),
                ),
            ],
        ),
    ]
