# Generated by Django 5.0.4 on 2024-05-03 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_gender'),
        ('core', '0003_rename_id_teacher_idx_alter_class_subjects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('idx', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Registration number')),
                ('role', models.CharField(choices=[(1, 'Administratives'), (2, 'Management staff'), (3, 'Business owner')], max_length=30, verbose_name='Admin role')),
            ],
        ),
    ]
