# Generated by Django 4.2.6 on 2023-12-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[
                    ("M", "Male"),
                    ("m", "male"),
                    ("F", "Female"),
                    ("f", "female"),
                ],
                max_length=10,
                verbose_name="Gender",
            ),
        ),
    ]
